apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecocycle-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecocycle
  template:
    metadata:
      labels:
        app: ecocycle
    spec:
      containers:
        - name: ecocycle-container
          image: akshithauser/ecocycle-react:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
